package isosceles;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;

/* This program writes an array to a text file generated by a given function before doing counting.
 * The programs depends on this program generated file is Count,Writerafter,Createimage.So,
 * before running them it is necessary to execute this one .
 * 
 *  In this code inputs are row,m,n.
 *  row stands for size of array
 *  m and n are parameters used in function
 *  
 *  You also have to change the file path according to your system*/

public class Writerbefore
{
	int row=1000,m=7,n=4;
	
	int i,j,count=0;
	double p=Math.PI,t=Math.sqrt(3),pi=(p/(row+1));
    double mul,a,b,c,d,e,f,xx,yy;
    int[][] matrix = new int [row][row];
    
    //This method calculates the given function and accordingly store output into an array in the form of 0 and 1. 
    private void sin()
    {
    	// TODO Auto-generated method stub
    	for (int i =0; i < row; i++)
    	{
    		for (int j = 0; j <row; j++) 
    		{
    			a=Math.sin((m*(i+1))*pi);
    			b=Math.sin((n*(j+1))*pi);
    			c=Math.sin((n*(i+1))*pi);
    			d=Math.sin((m*(j+1))*pi);
    			mul=(a*b)-(c*d);
    			if(mul<0)
    			{
    				matrix[i][j]=0;
    			}
    			else
    			{
    				matrix[i][j]=1;
    			}
    		}
    	}
    	

    } 
    // This method is used to cut down the isosceles triangle from the matrix generated by sin() method. 
    private void tri() 
    {
    	// TODO Auto-generated method stub
    	for (int i = 0; i < row; i++)
    	{
    		for (int j = 0; j < row; j++)
    		{
    			if(i>j)
    			{
    				matrix[i][j]=matrix[i][j];
    			}
    			else
    			{
    				matrix[i][j]=3;
    			}
    		}
    	}

    }
    // This method writes the generated matrix to a text file.
	private void write() throws IOException 
	{
		// TODO Auto-generated method stub
		StringBuilder builder = new StringBuilder();

		for(int i = 0; i < row; i++)
		{
		for(int j = 0; j < row; j++)
		{
			if(i>=j)
		builder.append(matrix[i][j]+"");//append to the output string
		if(j < row - 1 && i>=j)//if this is not the last row element
		builder.append(",");// separator used in between elements 
		}
		builder.append("\n");//append new line at the end of the row
		}
		BufferedWriter writer = new BufferedWriter(new FileWriter("iso/"+m+","+n+"isobefore.txt"));// file name for generated file
		writer.write(builder.toString());//save the string representation of the board
		writer.close();

System.out.println("saved");

	}
	public static void main(String[] args) throws IOException 
	{
		Writerbefore n=new Writerbefore();
		n.sin();
		n.tri();
		n.write();
		
	
	}

}
