package square;


import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

/* This program writes an array to a text file generated by a given function before doing counting.
 * The programs depends on this program generated file is Count,Writerafter,Createimage.So,
 * before running them it is necessary to execute this one .
 * 
 *  In this code inputs are row,m,n.
 *  row stands for size of array
 *  m and n are parameters used in function
 *  
 *  You also have to change the file path according to your system*/

public class Writerbefore
{
	int row=1000,m=15,n=4;
	
	int i,j,count=0;
	double p=Math.PI,t=Math.sqrt(3),pi=(p/(row+1));
    double mul,xx,yy;
    int[][] matrix = new int [row][row];
    
  //This method calculates the given function and accordingly store output into an array in the form of 0 and 1. 
    private void sin()
	{
		// TODO Auto-generated method stub
		for (int i =0; i < row; i++)
		{
			for (int j = 0; j <row; j++) 
			{
				xx=((i+1)*pi);
				yy=((j+1)*pi);
				mul=Math.sin(m*xx)*Math.sin(n*yy);
				if(mul<0)
				{
					matrix[i][j]=0;
				}
				else
				{
					matrix[i][j]=1;
				}
			}
		}
	} 
    // This method writes the generated matrix to a text file.
  	private void write() throws IOException 
	{
		// TODO Auto-generated method stub
		StringBuilder builder = new StringBuilder();

		for(int i = 0; i < row; i++)
		{
		for(int j = 0; j < row; j++)
		{
		builder.append(matrix[i][j]+"");//append to the output string
		if(j < row - 1)//if this is not the last row element
		builder.append(",");// separator used in between elements 
		}
		builder.append("\n");//append new line at the end of the row
		}
		BufferedWriter writer = new BufferedWriter(new FileWriter("square/"+m+","+n+"squarebefore.txt"));// file name for generated file
		writer.write(builder.toString());//save the string representation of the board
		writer.close();
		System.out.println("saved");
	}
	public static void main(String[] args) throws IOException 
	{
		Writerbefore n=new Writerbefore();
		n.sin();
		n.write();
		DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
		Date date = new Date();
		System.out.println(dateFormat.format(date));
	}

}
